/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class", // <--- important for dark mode!
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    // If you use src directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ee7d77",
        "primary-fixed-dim": "#5fedb0",
        "surface-dim": "#0e0e0e",
        "on-tertiary": "#006444",
        "surface-container-high": "#1f2020",
        "on-surface": "#e7e5e4",
        "on-error-container": "#ff9993",
        "secondary-container": "#2e3c50",
        "secondary-fixed": "#d5e3fd",
        "on-secondary": "#122133",
        "tertiary-fixed": "#7ff3be",
        "inverse-surface": "#fcf9f8",
        "on-tertiary-fixed": "#00452e",
        "on-background": "#e7e5e4",
        "on-primary-fixed": "#004930",
        "primary-container": "#005236",
        "surface-bright": "#2c2c2c",
        "secondary-fixed-dim": "#c7d5ee",
        "on-primary-container": "#5ae9ac",
        "error-container": "#7f2927",
        "surface": "#0e0e0e",
        "inverse-primary": "#006d4a",
        "on-error": "#490106",
        "on-tertiary-fixed-variant": "#006545",
        "outline-variant": "#484848",
        "surface-variant": "#252626",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#b2c0d9",
        "error-dim": "#bb5551",
        "inverse-on-surface": "#565555",
        "tertiary": "#9bffcf",
        "secondary": "#909fb6",
        "on-tertiary-container": "#005a3d",
        "outline": "#767575",
        "on-primary": "#004a31",
        "primary-dim": "#3cd096",
        "surface-container-low": "#131313",
        "tertiary-container": "#7ff3be",
        "on-secondary-fixed-variant": "#4e5c71",
        "primary": "#4edea3",
        "surface-container-highest": "#252626",
        "tertiary-fixed-dim": "#71e4b1",
        "on-primary-fixed-variant": "#006947",
        "tertiary-dim": "#71e4b1",
        "on-surface-variant": "#acabaa",
        "background": "#0e0e0e",
        "surface-container": "#191a1a",
        "surface-tint": "#4edea3",
        "secondary-dim": "#909fb6",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#324054"
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-space-grotesk)", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
    },
  },
  plugins: [],
}
